blank_issues_enabled: false
contact_links:
  - name: General discussion
    url: https://github.com/leekelleher/umbraco-package-ideas/discussions/new?category=general
    about: For suggestions and feedback about this project.
